millications<-function(WR){
  #' Calculate the millication composition of a rock
  #' @param WR A WR major element composition expressed as oxides.
  #' It can be given in any sensible form including matrix, data.frame and (named) vector
  #' @return A data.frame of millication proportions
  #' @details
    #' Millications are calculated for all "known" oxides, in GCDmodel::petroOxides
    #' The resulting value is NOT normalized (not guaranteed to sum up to 1 or anything special)
  #' @export
  #' @details
    #' This makes NO CHECKS on the presence of fe2/fe3 forms or Fe,
    #' use cleanCats() to be sure.
    #'

  # Make sure we deal with data frame
  if(is.matrix(WR)){
    WR <- as.data.frame(WR)
  }

  if(is.vector(WR)){
    WR <-  as.data.frame.list(WR)
  }

  existingOxides <- intersect(rownames(petroOxides),names(WR))

  eee<-apply(WR[,existingOxides],
             MARGIN=1,
             FUN = function(z){z / petroOxides[existingOxides,"OxideMass"] * petroOxides[existingOxides,"NbCations"] * 1000 } )

  milli <-data.frame(t(eee))
  milli[is.na(milli)] <- 0
  rownames(milli) <- rownames(WR)

  return(milli)
}


cleanCats<-function(milli){
    #' This function makes sure FeOt exists (it is required downstream by M)
    #' It could also be used to do further cleanup
    #' @param milli a table containing millications. It could be a data.frame
    #' (for instance generated by GCDmodel::millications() ), a matrix
    #' (such as generated by GCDkit::millications() ) or a vector.
    #' @return a data.frame with the same values, plus FeOt.
    #' @export

  ## Make sure we deal with data frame
  if(is.matrix(milli)){
    milli <- as.data.frame(milli)
  }

  if(is.vector(milli)){
    milli <-  as.data.frame.list(milli)
  }

  # We have to clean for various sorts of Fe

  oxd<-colnames(milli)
  if(!("FeOt" %in% oxd)){
    # FeOt is missing, we must do something !
    if(any(colnames(milli)=="FeO")){fe2<-milli[,"FeO"]}else{fe2<-0}
    if(any(colnames(milli)=="Fe2O3")){fe3<-milli[,"Fe2O3"]}else{fe3<-0}
    FeOt<-fe2+fe3
    milli<-cbind(milli,FeOt)
  }

   return(milli)
}
