##### Zircon saturation code #####
#
# Various functions to calculate the T.Zr.sat and the Zr.sat of the system
#
######

M_param <- function(cats){
  #' Calculate the M parameter, as used by various zircon saturation equations
  #' @param cats a data.frame containing the cationic proportions,
  #' probably generated by millications()

  # Filter the cats variable, keep only legitimate oxides
  oxides<-c("SiO2","TiO2","Al2O3","FeOt",
            "MnO","MgO","CaO","Na2O","K2O","P2O5")
  cats<-cats[,intersect(oxides, colnames(cats)),drop=FALSE]
  # oxides<-oxides[oxides%in%colnames(cats)]
  # cats<-cats[,oxides,drop=FALSE]

  # Normalize to 1
  sums<-apply(cats,1,sum,na.rm=TRUE)
  ee<-sapply(1:nrow(cats),function(i){
    z<-cats[i,]/sums[i]
    return(z)
  })
  cats<-t(ee)

  # The parameter
  M<-(cats[,"Na2O"]+cats[,"K2O"]+2*cats[,"CaO"])/(cats[,"Al2O3"]*cats[,"SiO2"])

  return(M)
  }


ZrSat_WH<-function(WR,TK=NULL,Zr=NULL){
  #' Zr saturation, Watson & Harrison (1983)
  #' Return (1) the [Zr] of a saturated liquid, at a given T;
  #' (2) the T saturation, at a given [Zr].
  #' If T, or [Zr], is not supplied, the resulting value will be NULL
  #' @param WR a data.frame or a matrix containing major element wt%
  #' (it should have only numeric values)
  #' @param TK: the temperature (in K)
  #' @param Zr: [Zr] concentration (ppm)
  #' @value A data.frame, containing M, Zr.sat_WH and T.Zrsat_WH

  milli <- millications(WR)
  M <- M_param(milli)

  # Temperature is known: return [Zr]sat
  if(!is.null(TK)){
    DZr<-exp(-3.8-0.85*(M-1)+12900/TK)
    Zr.sat<-497644/DZr
  }else{
    Zr.sat <- NULL
  }

  # [Zr] is known: return Tsat
  if(!is.null(Zr)){
    DZr<-497644/Zr
    DZr<-as.vector(DZr)
    TZr.sat<-12900/(log(DZr)+3.8+0.85*(M-1))
  }else{
    TZr.sat<-NULL
  }

  return(data.frame(M=M,
              Zr.sat_WH=Zr.sat,
              TZr.sat_WH=TZr.sat ))
  }


ZrSat_Boehnke<-function(WR,TK=NULL,Zr=NULL){
  #' Zr saturation, Boehnke et al. (2013)
  #' Return (1) the [Zr] of a saturated liquid, at a given T;
  #' (2) the T saturation, at a given [Zr].
  #' If T, or [Zr], is not supplied, the resulting value will be NULL
  #' @param WR a data.frame or a matrix containing major element wt%
  #' (it should have only numeric values)
  #' @param TK: the temperature (in K)
  #' @param Zr: [Zr] concentration (ppm)
  #' @value A data.frame, containing M, Zr.sat_Boehnke and T.Zrsat_Boenhke

  milli <- millications(WR)
  M <- M_param(milli)

  # Temperature is known: return [Zr]sat
  if(!is.null(TK)){
    DZrB<-exp(10108/TK-1.16*(M-1)-1.48)
    Zr.sat<-497644/DZrB
  }else{
    Zr.sat <- NULL
  }

  # [Zr] is known: return Tsat
  if(!is.null(Zr)){
    DZrB<-497644/Zr
    DZrB<-as.vector(DZrB)
    TZr.sat<-10108/(log(DZrB)+1.16*(M-1)+1.48)
  }else{
    TZr.sat<-NULL
  }

  return(data.frame(M=M,
              Zr.sat_Boehnke=Zr.sat,
              TZr.sat_Boehnke=TZr.sat ))
}


zrSaturation<-function(WR,T=0,Zr=filterOut(WR,"Zr",1)){
  #' Temporary placeholder

  WH <- ZrSat_WH(WR,TK=T,Zr)
  Boehnke <- ZrSat_Boehnke(WR,TK=T,Zr)

  y <- cbind(WH$M,Zr,
             round(WH$Zr.sat_WH,1),
             round(WH$TZr.sat_WH-273.15,1),
             round(Boehnke$Zr.sat_Boehnke,1),
             round(Boehnke$TZr.sat_Boehnke-273.15,1)
             )

  # y<-cbind(M,Zr,round(Zr.sat,1),round(TZr.sat.C,1),
  #          round(Zr.satB,1),round(TZr.satB.C,1))
  colnames(y)<-c("M","Zr.obs","Zr.sat","TZr.sat.C","Zr.sat (Boehnke)","TZr.sat.C (Boehnke)")
  # if(nrow(y)>1) y<-formatResults(y) else rownames(y)<-rownames(cats)
  # if(!getOption("gcd.shut.up"))print(y)
  # assign("results",y,.GlobalEnv)
  invisible(y[,-2])
}
